version: '3'
services:
  db:
    image: postgres:11.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/photo-app
      - public-data:/photo-app/public
    ports:
      - "3000:3000"
    depends_on:
      - db
  server:
    build:
      context: containers/nginx
    volumes:
      - ./nginx/log:/var/log/nginx
      - public-data:/photo-app/public
    depends_on:
      - web
    ports:
      - 80:80
volumes:
  public-data:
  postgresql-data:
    driver: local