default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>

development:
  <<: *default
  database: photo-app_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: photo-app_production
  username: photo-app
  password: <%= ENV['PHOTO-APP_DATABASE_PASSWORD'] %>