default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: myapp_development

production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>
  database: <%= ENV.fetch("POSTGRES_DB") { 'myapp_test' } %>